### PR TITLE
DevanshD3

### PR DESCRIPTION
**Pull request by DevanshD3**
I was assigned this issue for hacktoberfest 2020.  Let me know if there's any problem!

### CODE REVIEW

**Comment by ion05** [comment]
Since you are doing this for hacktoberfest 2020, I suggest you open the PR in October only. Otherwise it won't count. And I am going to need a screenshot of your code working. Run it on ur usual IDE and send me a screenshot

**Comment by GobindAnand** [comment]
yes do it in oct only

**Comment by ion05** [comment]
@GobindAnand such comments are unnecessary and not appreciated. If you do such an act again, I will ban you from this repository

**Comment by DevanshD3** [comment]
@ion05 sure sure! So should I create a pull request again? Or you will merge it tomorrow? And should I send the screenshot now today or tomorrow ?

**Comment by ion05** [comment]
1) Please create folder with ur github username and put your python folder in their. 
2) I will close this PR and you will have to open a new one tomorrow. In that PR attach a screenshot

**Comment by DevanshD3** [comment]
Sure thanks a lot !! I will do that at 12:01 AM IST.

**Comment by ion05** [comment]
I advise you to do it in the day. Just in case because no one(including hacktoberfest staff) knows the exact timezone according to which the PRs will be counted.

**Pull request closed without merging**
