### PR TITLE
Anagram

### PR DESCRIPTION
**Pull request by subhash1612**
Anagram code and screenshot has been added

### CODE REVIEW

**Comment by ion05** [comment]
Please share the screenshot here itself and don't add it as a file in the PR

**Comment by subhash1612** [comment]
Do I need to create a new pull request or just attach the file here. Sorry,I am new to opensource.

**Comment by subhash1612** [comment]
changes have been made.
image file:
anagram

**Comment by ion05** [comment]
Good. Since you are a newbie, i advise you to ALWAYS attach a screenshot in ur PRs.

**Pull request merged**
