### PR TITLE
Adding Fibonacci Series

### PR DESCRIPTION
**Pull request by navya678**
Hi,
   I have just added my Fibonacci code with Result snapshot.

### CODE REVIEW

**Comment by navya678** [comment]
Hi, 
   I have also included Anagrams code with Result.

**Comment by yuvraajnarula** [comment]
Pls send the screenshot of the working of the code.

**Comment by navya678** [comment]
Anagrams_Result
Fibonacci_Result

**Comment by navya678** [comment]
Hi there, 
         May I know the reason why my code wasn't labelled with hackotberfest or hacktoberfest-accepted? I'm new to Opensource contribution. Thanks in Advance!

**Comment by ion05** [comment]
I am sorry for that error on our side.

**Comment by navya678** [comment]
> I am sorry for that error on our side.

Not a problem! Thanks a lot.

**Pull request merged**
