### PR TITLE
file containing all code for calculator.py and anangram.py

### PR DESCRIPTION
**Pull request by eaglewarrior**
code for issue #2 please review and let me know if anything else is required

### CODE REVIEW

**Review by ion05 — APPROVED** [review]

**Review by ion05 — CHANGES_REQUESTED** [review]
Pls share the screenshot of it working

**Comment by eaglewarrior** [comment]
> Pls share the screenshot of it working
@ion05 
image

**Comment by eaglewarrior** [comment]
> Pls share the screenshot of it working

image

**Comment by ion05** [comment]
Great

**Comment by eaglewarrior** [comment]
please can u label hacktoberfest-accepted @ion05

**Comment by eaglewarrior** [comment]
@ion05  please add hacktoberfest accepted label

**Pull request merged**
