### PR TITLE
add simple_calculator

### PR DESCRIPTION
**Pull request by Ajit-53**

### CODE REVIEW

**Comment by ion05** [comment]
Please share a screenshot

**Comment by Ajit-53** [comment]
Screenshot (279)

**Comment by ion05** [comment]
Please follow the steps given in README.md

**Comment by Ajit-53** [comment]
if you dont want to add ..plz dont add it..but why you gives invalid ...

**Comment by ion05** [comment]
Because your attempted contribution was not in line with the guidelines laid down in README.md

**Pull request closed without merging**
