### PR TITLE
Tic-tac-toe in python

### PR DESCRIPTION
**Pull request by smish-hash**
This one would contain my tic-tac-toe game in python as a part of my Hactoberfest 2020 entry

### CODE REVIEW

**Comment by ion05** [comment]
Please share a screenshot

**Comment by smish-hash** [comment]
I have pasted two screenshots for the tic tac toe game in the the tic tac toe folder

**Comment by ion05** [comment]
Please share the screenshots here

**Comment by smish-hash** [comment]
Anagram
anagram_output

Tictactoe 
tictactoe Screenshot (228)
tictactoe Screenshot (229)

**Pull request merged**
