### PR TITLE
TicTacToe Solution

### PR DESCRIPTION
**Pull request by TheCoderNikhil**
Solution For Tic Tac Toe Program By The Coder Nikhil
Here is the working screen shot of the code,

image

### CODE REVIEW

**Comment by ion05** [comment]
Are you doing this for HacktoberFest 2020 ?

**Comment by TheCoderNikhil** [comment]
@ion05 Yes I am Doing For Hacktober Fest 2020

**Comment by TheCoderNikhil** [comment]
@ion05  Please  Accept My request

**Comment by ion05** [comment]
Please follow the steps established in README.md

**Pull request closed without merging**
