### PR TITLE
Shrey's Python Programs

### PR DESCRIPTION
**Pull request by shreykpatnaik**
I completed the python programs for anagram and tic tac toe game. It was fun!

### CODE REVIEW

**Comment by yuvraajnarula** [comment]
can you please share the screenshot of working of your code

**Comment by shreykpatnaik** [comment]
[https://kiitacin-my.sharepoint.com/:f:/g/personal/1928120_kiit_ac_in/Elcl-OmT3H1JqIbyECltMR0BuH2WEzSZ3scL03ZnaGaglA?e=wf8tB9](url)

**Pull request merged**
