### PR TITLE
added a simple gui calculator

### PR DESCRIPTION
**Pull request by anoop447**
made a graphical user interface calculator using Tkinter.

### CODE REVIEW

**Comment by ion05** [comment]
Please share a screenshot

**Comment by anoop447** [comment]
output srcnshot

**Comment by anoop447** [comment]
Hello
I hope I have done this work correctly. As this was my first ever PR. 
I attached a screenshot as u said.

**Comment by anoop447** [comment]
can you please merge my contribution.

**Comment by ion05** [comment]
Please be patient. Your contribution will be merged. Even if its not , it will still count for Hacktoberfest

**Pull request merged**
