### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by TheCoderNikhil**
The Simple Calculator Solution, Using Python By The Coder Nikhil

### CODE REVIEW

**Comment by TheCoderNikhil** [comment]
### HERE IS THE SCREEN SHOT OF WORKING PROGRAM
Working

**Comment by ion05** [comment]
Are you doing this for HacktoberFest 2020 ?

**Comment by TheCoderNikhil** [comment]
Yes, I am Doing For Hacktober Fest 2020, Please Merge It, Fast as it is working

**Comment by ion05** [comment]
This PR wont be merged as it is not in line with the steps clearly laid down in README.md

**Pull request closed without merging**
