### PR TITLE
completed the anagram problem using python

### PR DESCRIPTION
**Pull request by smish-hash**
This is a part of my submission for hactoberfest 2020.
This was my first time trying to solve the anagram problem.

### CODE REVIEW

**Comment by ion05** [comment]
Please share a screenshot

**Comment by smish-hash** [comment]
The screenshot is there inside smish-hash/ anagram problem

**Comment by ion05** [comment]
Please share the screenshots here

**Comment by smish-hash** [comment]
Anagram
anagram_output

Tictactoe
tictactoe Screenshot (228)
tictactoe Screenshot (229)

**Pull request merged**
